# Generated by Django 4.0.3 on 2022-04-20 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myfirst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detailsuser',
            fields=[
                ('userdetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('money', models.IntegerField(default='0')),
                ('oplatil', models.CharField(max_length=1000)),
                ('temporaryamount', models.IntegerField(default=0, help_text='Если пользователь не оплатил', verbose_name='Временная сумма:')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('product', models.CharField(max_length=100)),
                ('useralot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('text', models.TextField()),
                ('prise', models.IntegerField()),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('docker_choose', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='VDSTARIFS',
        ),
    ]
