# Generated by Django 4.0.3 on 2022-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0002_blog_detailsuser_prices_delete_vdstarifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='userconnect',
            field=models.ManyToManyField(to='myfirst.detailsuser'),
        ),
    ]
