# Generated by Django 4.0.3 on 2022-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0003_prices_userconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
