# Generated by Django 4.0.3 on 2022-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0004_prices_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
